### ISSUE TITLE
[Expression propagation] refactor EP-related stages

### ISSUE THREAD

**Issue by mari-mari** [fkie-cad/dewolf#198]
### Proposal

Refactor `ExpressionPropagation`, `ExpressionPropagationMemory` and `ExpressionPropagationFunctionCalls`.

### Approach

Check if it is possible to use cfg directly instead of computing use and def map. If possible, group corner cases so that the corresponding stages functionality could be easier understood and updated.

**Comment by steffenenders** [comment]
I don't think that we should create issues with the sole purpose of refactoring.
