### ISSUE TITLE
[Preprocessing] Stack canary check found in __stack_chk_fail

### ISSUE THREAD

**Issue by 0x6e62** [fkie-cad/dewolf#243]
### What happened?

When decompiling any elf file with stack canary checks, the function `__stack_chk_fail` will fail to decompile since the stage in `remove_stack_canary.py` will try to remove its single basic block based on it detecting a reference to `__stack_chk_fail` in it.

https://bugfinder.seclab-bonn.de/case/81/

### How to reproduce?

> python decompile.py /bin/ls __stack_chk_fail --debug

### Affected Binary Ninja Version(s)

3

**Comment by mm4rks** [comment]
see https://github.com/fkie-cad/dewolf/issues/248 (duplicate)
