### ISSUE TITLE
[For-Loop Reconstruction] Not handling "continue" instructions correctly

### ISSUE THREAD

**Issue by ebehner** [fkie-cad/dewolf#247]
### What happened?

Consider the following c-code snippet:
```c
int test12()
{
    int i = 0;
    while(i< 10){
        printf("The current number is %d\n", i);
        if(i == 2){
            i += 2;
            continue;
        }
        i += 1;
    }

    return 0;
}
```
Currently (8703988), the decompiler output is:
```c
int test12() {
    int i;
    for (i = 0; i <= 9; i += 2) {
        printf(/* format */ "The current number is %d\n", i);
        if (i != 2) {
            i++;
            continue;
        }
    }
    return 0;
}
```

But, after the continue statement, the variable `i` is still increased by 2. The output of the decompiler code would be:
```bash
The current number is 0
The current number is 3
The current number is 6
The current number is 9
```
whereas the output should be the following:
```bash
The current number is 0
The current number is 1
The current number is 2
The current number is 4
The current number is 5
The current number is 6
The current number is 7
The current number is 8
The current number is 9
```

#### Problem description
After the restructuring, the AST looks as follows:
![ast](https://github.com/fkie-cad/dewolf/assets/7224664/3eaa604b-a86d-4886-a155-7fd1dec8bfd7)
Now, the last instruction is `var_0 = var_0 + 2` and we have the initialization `var_0 = 0`. Thus, we transform the while-loop into a for-loop. The problem is the continue-statement. After the continue-statement, we still update the for-loop counter.

#### Possible Solution
1. Only do for-loop reconstruction, if there is no continue in the loop body
2. Check that the update-statement rule also holds when continuing the loop due to a continue-statement. 

### How to reproduce?

Decompiler `test12` from the following sample [test_loop.zip](https://github.com/fkie-cad/dewolf/files/11719085/test_loop.zip)

### Affected Binary Ninja Version(s)

3.4.4225-dev

**Comment by fnhartmann** [comment]
Created a separate follow-up issue: #325
