### ISSUE TITLE
False control structure for structs

### ISSUE THREAD

**Issue by NeoQuix** [fkie-cad/dewolf#256]
### What happened?

Decompile `f` from [a.out.tar.gz](https://github.com/fkie-cad/dewolf/files/11785172/a.out.tar.gz). 

Expected result:
Correct control flow with the two struct variables.

Got: 
```c
long f(long arg1) {
    long lVar1;
    lVar1 = 0L;
    return lVar1;
}
```

Src:
```C
struct MyCoolStruct{
    int a, b;
    char* ptr;
};

int f(struct MyCoolStruct arg){
    if(arg.a == 12 && arg.b == 13)
            return 1;
    return 0;
} 
``

The two constants are propagated into the phi function. 
Outofssa replaces the phi function with arg1= 0x0. 

### How to reproduce?

Decompile f 

### Affected Binary Ninja Version(s)

3.4.4271

**Comment by rihi** [comment]
This is caused by `MediumLevelILVarField` being lifted incorrectly, which caused the condition `arg.b == 13` to be evaluated as unsatisfiable. This causes the whole `return 1` branch to be optimized away.
