### ISSUE TITLE
Adjust code generation for the function pointer type.

### ISSUE THREAD

**Issue by mari-mari** [fkie-cad/dewolf#322]
### Proposal

Binary Ninja knows that `arg3` is a function pointer, and correctly types it in the signature of `_start`:
```c
 int64_t _start(int64_t arg1, int64_t arg2, void (* arg3)())
```

I think we get this information but produce incorrect signature (`void()`):
```c
long _start(long arg1, long arg2, void() * arg3) {
    void var_2;
    long var_3;
    var_3 = var_0;
    __libc_start_main(main, var_1, /* envp) */ &var_2, __libc_csu_init, /* ubp_av */ __libc_csu_fini, /* init)() */ arg3, /* fini)() */ &var_3);
}
```

### Approach

Correct typing of the function pointers in the function arguments.
Without digging into the code, I assume it is just the issue with the way we generate code for the function pointer types.

If this is not the case, we should examine how we lift the function pointer type (and change the title of the issue).

**Comment by mari-mari** [comment]
FYI @martinclauss

**Comment by NeoQuix** [comment]
After looking a bit more into the code:
- a check for that type will be the easiest and ugliest way
- a better way would have been to use the `__str__` representation of `Variable` for the code generator, like it's done for types, but that is not possible anymore

Wasn't there a suggestion to rewrite the backend?
