### ISSUE TITLE
What did I do wrong

### ISSUE THREAD

**Issue by imethod** [fkie-cad/dewolf#345]
### Question

![image](https://github.com/fkie-cad/dewolf/assets/109936536/dfc40d79-9f67-40f1-b13d-d5cca418f4ed)

**Comment by NeoQuix** [comment]
Did you install DeWolf inside a virtual environment?
If so, then go into binary ninja setting and set the "Python Virtual Environment Site-Packages" onto the correct site-packages path of your virtual env.

**Comment by imethod** [comment]
> Did you install DeWolf inside a virtual environment? If so, then go into binary ninja setting and set the "Python Virtual Environment Site-Packages" onto the correct site-packages path of your virtual env.

thankes The ninja problem
