### ISSUE TITLE
consider pushing a new release?

### ISSUE THREAD

**Issue by psifertex** [fkie-cad/dewolf#384]
### Proposal

Sounds like the current version in the Plugin Manager isn't installable with the latest release but that the plugin that exists on GH is. Is it possible to push a [new release](https://binary.ninja/2019/07/04/plugin-manager-2.0.html#5-create-a-release) so the newer changes are more discoverable?

**Comment by psifertex** [comment]
Thanks! This looks like a great improvement. Is it possible to trigger a release now to get a fresh release or is the plan to just wait for the next one to trigger it?

**Comment by steffenenders** [comment]
> Thanks! This looks like a great improvement. Is it possible to trigger a release now to get a fresh release or is the plan to just wait for the next one to trigger it?

Since we're still dealing with a few issues related to the Binary Ninja 4.0 update anyways, I'm leaning towards just waiting for the first automated release in April.

**Comment by psifertex** [comment]
No problem. Let me know if I can be of assistance.
