### ISSUE TITLE
Loop Config Options

### ISSUE THREAD

**Issue by steffenenders** [fkie-cad/dewolf#66]
### Proposal

Add configuration options for (for-loops). Right now, I can think of the following options that we probably should add to dewolf:
* Loop Variable Names (specify which kind of variable names should be used for for-loops)
* Conditions for for-loop recovery:
    * Maximum complexity for a condition to be allowed in a for-loop header.
    * Maximum complexity for a modification statement to be allowed in a for-loop header.
    * Some option like: `force for-loops` which always transforms a loop to a for-loop, if possible.

**Comment by NeoQuix** [comment]
### Approach
1. _Loop Variable Names (specify which kind of variable names should be used for for-loops)_
	- change config option `rename_for_loop_variables` from boolean to list of strings
	- list will be given to `ForLoopVariableRenamer` and uses as `candidates`
2. _Maximum complexity for a condition to be allowed in a for-loop header_
	- conditions containing only AND statements could be just negated and moved into the corpse with a `break` statement behind (maybe split each condition after X complexity into own `if(!cond_i){break}`?)
	- for cases with OR statements another approach would be needed
3. _Maximum complexity for a modification statement to be allowed in a for-loop header_
	1. Do you mean complexity for one variable modification?
		-  if that's the case a few examples would be great
	2. Or complexity in term of more then one variable modification/initialization
		- as for now the decompiler can only have __one__ init/continuation statement in for loop (if i see correctly)
		- ==> maybe let more then one init/continuation statement be in a for loop and then a config option?
4. _Some option like: force for-loops which always transforms a loop to a for-loop, if possible._
	- would someone actually want that? or a better question: "Would that really improve readability?"
	- i mean the easiest way (that would work for any loop type; after the WhileLoopReplacer has done it's work) would be
		- `while(cond){...}` ==> `for(;cond;){...}`
		- `do{...}while(cond)` ==> `for(;true;){...if(!cond){break}}`
	- doesn't look any better to be honest :)
