### ISSUE TITLE
Survey samples?

### ISSUE THREAD

**Issue by skochinsky** [fkie-cad/dewolf#88]
### Question

Could you share the binary samples you used to prepare output for surveys mentioned in [the paper](https://arxiv.org/abs/2205.06719), or at least the compile options? For example, the figure labeled "Output generated with Hex-Rays and IDA 7.5.200728 (SP2)" looks somewhat suspect and not like typical Hex-Rays  output.

**Comment by steffenenders** [comment]
Yes, of course. For the samples, please refer to the following repository: https://github.com/steffenenders/dewolf-surveys
There you will find all three samples we used for the survey.

Keep in mind that we removed some linebreaks and whitespaces from the output to save space (as mentioned in the paper).

**Comment by steffenenders** [comment]
I hope, this answers your question. If not, feel free to re-open this issue or contact me directly :)
