### ISSUE TITLE
Request Integration with Decompiler Explorer / DogBolt

### ISSUE THREAD

**Issue by FelixBer** [fkie-cad/dewolf#95]
### Proposal

Request integration with decompiler explorer: https://dogbolt.org/

As I understand it, the request must be made by product owners of new decompilers by opening an issue at https://github.com/decompiler-explorer/decompiler-explorer/issues or contacting them directly.
Added benefit - you gain access to binaries uploaded to the service.

intro blogpost: https://binary.ninja/2022/07/13/introducing-decompiler-explorer.html

**Comment by steffenenders** [comment]
Hi! Yes, I was actually already planning to create a pull-request for this. I hope I will have enough time next week :)

**Comment by CouleeApps** [comment]
I've started an implementation of this, but ran into a couple bugs as mentioned in that issue. If y'all want to address them (or just release as-is) go ahead-- I'll merge it when you think it's good.

**Comment by steffenenders** [comment]
> I've started an implementation of this, but ran into a couple bugs as mentioned in [that PR](https://github.com/decompiler-explorer/decompiler-explorer/pull/73). If y'all want to address them (or just release as-is) go ahead-- I'll merge it when you think it's good.

Thank you very much for your efforts! I just pushed the requested patch for the `requirements.txt`.

Regarding the thrown exceptions: We are aware that there are still many stability issues we have to fix for dewolf.
We hope that we can use the uploaded binaries (from dogbolt) to fix many of those bugs - so we would love to get our hands on the binaries that crashed during your tests :) 
I assume that in case of any thrown exceptions while decompiling a function the output will still contain the output for the successfully decompiled functions - if that's the case, we are happy with you merging your PR.

**Comment by steffenenders** [comment]
dewolf is now available on https://dogbolt.org/
